src/Entity/Booking.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date d'arrivée doit étre au bon format !")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à la date d'aujourd'hui !",
     * groups={"front"})
     */
    // Parametre Groups Permet de définire les groupes dans lesquels se place une validation
    // le simple fait de metre ça , groups={"front"} cella veut dire que on a pas validation de securyte et sur le front 
     
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date de départ doit étre au bon format !")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être plus éloignée que la date d'arrivée !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;
    
    /**
     * Callback appelé à chaque fois qu'on crée une réservation
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function prePersist() {
        // si ma date de creation elle est vide 
        if(empty($this->created)) {
        // et bien j'ai en vie que ca devient la nouvelle DateTime
           $this->createdAt = new \DateTime();
        }

        // maintenat on calcule le montant 
        // si le montant est vide 
        if(empty($this->amount)) {
            // alors on doit calculet 
            // prix de l'annonce * nombre de jour 
            // on stocke tout dans $this->amount que on a declare ici
            $this->amount = $this->ad->getPrice() *  $this->getDuration();
        }

    }


    public function isBookableDates() {
        // ici avec la function function isBookableDates()  on demande si ces datte sont posibles pour réserver
       // 1) Il faut  connaitre les dates qui sont impossible pour l'annonce
       $notAvailableDays = $this->ad->getNotAvailableDays(); // ici on chope les journe pour la quel cette annonce ne serra pas disponible
       // 2) Il faut comparer les dates choisies avec les dates imposibles 
       $bookingDays = $this->getDays(); // ici se l'ensemble de journées de ma réservation sur format de tableau DateTime


       $formatDay = function($day){
        return $day->format('Y-m-d');
       };

       // Tableau des chaînes de caractères de mes journées
       // je transforme mes objets dateTime de ma réservation en chaînes de caractères Y-m-d
       $days = array_map($formatDay, $bookingDays);

       // ici je fait la meme chose mais pour les journées qui sont pas 
       // disponible ce qui fait que j'ai deux tableu de chaînes de catactères de Datetime
       $notAvailable = array_map($formatDay, $notAvailableDays);

       // si on retrouve pas une de nous journe disponible ici 
       // donc je vais boucle sur chaque journées qui me conserne moi ma réservation
        // es que elle est presénte par mis les journées qui ne sont pas disponible
       foreach($days as $day) {
           // si se le cas ma function dit tout ça ne pas posible 
           if(array_search($day, $notAvailable) !== false) return false;
       }
       // si non la on return true pour me dire que tout a belle et bien functioner
       return true;
    }

    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation
     *
     * @return array Un tableau d'objets DateTime représentent les jours de la réservation
     */
    public function getDays() {
         $resultat = range(
             $this->startDate->getTimestamp(),
             $this->endDate->getTimestamp(),
             24 * 60 * 60 
         );

        // la on transforme chaque une de date reçu dans le range onn le tansforme dans une Timestamp ici avec la function map
        $days = array_map(function($dayTimestamp){
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat); // ici on precise le nom de tableu que on veut modifier ici ce (resultat)

        return $days;
    }

    public function getDuration() {
        // on declarre une variable diff que fait referance a la
        // differance entre endDate et startDate qui est considere comment un interval entre les deux date
        // méthode diff des objets DATATIME
        // Fait la diférance entre 2 dates et renvoie un objet DateInterval
        $diff = $this->endDate->diff($this->startDate);

        // ici on demande le retur de differance entre les jours
        // on regarde le nombre des jours qui sont eculler entre la date de arrive et celle de depart
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;



// ici on fait la premier validation  pour que les utilisateur soit unique en bdd 
// cette validation se de back-end par Symfony pas comme le requirements en html

// @Unique est une securyte en plus que on fait appel a elle pour verifier si dans l'Entite de User
// les email et le mdp soit unique et de pas avoir de doublon
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * Le @ORM\HasLifecycleCallbacks() dit fait attention cette entite posede de function
 * a appele pandent les evenement de cycle de vie de cette entité
 * 
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur s'est déjà inscrit avec cette adresse email, merci de la modifier"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénoms")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez donner une URL valide pour votre avatar !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;
    
    /**
     * ici permet de dire que EqualTo(propertyPath="hash" 
     * veut dire que le password confirm soit egale au hash
     * 
     *@Assert\EqualTo(propertyPath="hash",message="Vous n'avez pas correctement confirme votre mot de passe !")
     * 
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre introduction doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="authot", orphanRemoval=true)
     */
    private $comments;

    
    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Permet d'initializer le Slug
     * 
     *@ORM\PrePersist
     *@ORM\PreUpdate
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        // Classe ArrayCollection de Doctrine
        // C'est surcouche de tableaux, avec plus de fonctionnalités
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles() {
        // Rappel: la function getRole()
        // Function imposée par l'interface UserInteface implémentée plus tôt
        // La mission de getRole() Appelée par le composant se sécurité pour connaitre las rôles d'un user
      $roles = $this->userRoles->map(function($role){
        // ici la function map va boucle sur chaque element et va le transforme pour afficher un title 
        // sur chaque role que la function vas passer la seule chose que elle va retenire ce le Title   
        return $role->getTitle();      
      })->toArray(); 

      // ici on demande les roles des user dans un tableau array
      $roles[] = 'ROLE_USER';
      
        return $roles;
    }

    public function getPassword(){
       return $this->hash; 
    }

    public function getSalt() {}

    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials(){}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthot($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthot() === $this) {
                $comment->setAuthot(null);
            }
        }

        return $this;
    }
    
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : {{ad.title}}!{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
{% endblock %}


{% block body %}
<div class="container">
    <h1>Réservez pour l'annonce : <em>{{ad.title}}</em></h1>

       <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}
           </strong>, dites nous tout, on s'occupe du reste !</p>

       {{ form_start(form) }}
    <div class="alert alert-light">
         <h2 class="h5">Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>
        <div class="row">

            <div class="col">
                {{ form_row(form.startDate) }}
            </div> {# fin div col 1 #}
               
            <div class="col">
                {{ form_row(form.endDate) }}
            </div> {# fin div col 2 #}

        </div> {# fin div row #}

        <h4 class="mt-2">Montant du séjur : <span id="amount">...</span> &euro;</h4>
            <span id="days">0</span> nuit(s) à {{ad.price | number_format(2, ',', ' ')}} &euro; par nuit
            {# ici le Filter number_format() on demande le chifre a virgule comment en php
            2 est considere comment 2 nombré qui sont separe par la virgule et l'espace 
            saura pour le nombre de millier que sont separe par un espace  #}
        
        <h4 class="mt-3">Vous avez un commentaire ?</h4>
            {{ form_row(form.comment) }}
 </div> {# fin div alert-light #}


       <h2>Vous avez terminé !</h2>
            <p>Vacances de rêve ? Hébergement pour le boulot ? Peu importe, on est avec vous !</p>
                   
          <button type="submit" class="btn btn-success">Je réserve !</button>

            {{ form_end(form) }}
</div> {# fin div container #}
{% endblock %}



{% block javascripts %}

 <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

<script>
   $(document).ready(function(){
       $('#booking_startDate, #booking_endDate').datepicker({
           format: 'dd/mm/yyyy',
           datesDisabled: [
               // ici on demande le forma de date en france de datte non disponible a la réservation 
               {% for day in ad.notAvailableDays %}
                   "{{ day.format('d/m/Y') }}",
               {% endfor %}
           ],
           // apartir de cette date on peut réserver 
           startDate: new Date()
       });

       $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
   });

   function calculateAmount() {
       // On chope les dates 
       const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
       // '$3-$2-$1'  $3 = annees  $2 = mois  $1 = jour 
       // nous avont une date exemple 18/08/2019
       // on demande à capture ce que on trouve et quand je trouve le premier antislash d on le capture et on le met entre les paranteze()
       //  (\d+)\/(\d+)\/(\d{4}) et la on crée une expresion reguliere de que il ya une \d on le capture 
       // et on veut le transformer en 2019-08-18
       const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
    
    // si il ya un startDate et une endDate  alors on fait la comparaison et si la  startDate et bien inferieur a endDate
    if(startDate && endDate && startDate < endDate){
        const DAY_TIME = 24 * 60 * 60 * 1000;
        // dans ce cas on veut l'interval en milli seconde en timpstamp 
        const interval = endDate.getTime() - startDate.getTime();
        // le nombré de nuit ou jours que on et dans l'appart  = interval diviser par les milli seconde de timestamp 
        // diviser le / 24h * par 60 minute * 60 seconde * par milli seconde 1000
        // const days = interval / 24 * 60 * 60 * 1000
        const days = interval / DAY_TIME;

        // calcule de montant par nuit
        const amount = days *  {{ ad.price }};

        $('#days').text(days);
        $('#amount').text(amount.toLocaleString('fr-FR'))
    }
   }
</script>


{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{booking.id}}{% endblock %}

{% block body %}

{% set ad = booking.ad %} {# variable pour les annonce #}
{% set author = ad.author %} {# variable pour l'auteur #}

 <div class="container">
   <h1 class="my-5">Votre réservation (n°{{booking.id}})</h1>

   {# on met ici en cas que dans l'url on appele avec le parametre 
   get withAlert = true j'aimerais que ça se affiche et si ça existe j'aimerais faire certain chose  #}
   {% if app.request.query.get('withAlert') %}
       <div class="alert alert-success">
            <h4 class="alert-heading">Bravo !</h4>
              <p>
               Votre réservation auprés de 
               <strong>
                 <a href="{{ path("user_show", {'slug' : author.slug}) }}">
                 {{author.fullName}}</a>
               </strong>
               pour l'annonce 
               <strong>
                  <a href="{{ path("ads_show", {'slug' : ad.slug}) }}">{{ ad.title }}</a>
               </strong>
               a bien été prise en compte !
              <p>
       </div> {# fin div alert-success #}
   {% endif %}

   <div class="row">
       <div class="col">
          <div class="alert alert-light">
           <h2>Détails</h2>
           {# la balise dl veut dire definition list dt = detail dd = description de ses enfants #}
           <dl class="row">
           {# ON Utilisez plutôt .row on <dl>et 
           utilisez des classes de colonnes de grille (ou mixins) sur its <dt>et ses <dd>enfants. #}
           <dt class="col-md-4">Numéro</dt>
           <dd class="col-md-8">{{booking.id}}</dd>
           <dt class="col-md-4">Date d'arrivée</dt>
           <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
           <dt class="col-md-4">Date de départ</dt>
           <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
           <dt class="col-md-4">Nombre de nuits</dt>
           <dd class="col-md-8">{{booking.duration}}</dd>
           <dt class="col-md-4">Montant total</dt>
           <dd class="col-md-8">{{booking.amount | number_format(2, ',', ' ')}} &euro;</dd> 
           {# avec | number_format(2, ',', ' ')}} on donne 2 decimale une vigule , et un espace #}
           <dt class="col-md-4">Commentaire</dt>
           <dd class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dd> 
           {# Filtre twig : Default() permet de donner une valeur par défaut lors de l'affichage d'une variable #}
           </dl>

           <hr>

          <h2 class="alert-heading">Votre hôte</h2>
          <div class="row mb-3">
              <div class="col-3 px-1">
                <img src="{{author.picture}}" class="avatar avatar-medium" alt="Avatar de {{author.fullName}}">
              </div> {# fin div col-3  de second row #}
              <div class="col-9">
                <h4>
                  <a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullName }}</a>
                </h4>
                {# on demande le nombre des annonce detenu par l'utilisateur qui est connecté  avec le filtre | length #}
                <span class="badge badge-primary">{{author.ads|length}} annonces</span>

              </div> {# fin div col-9 de second row #}
          </div> {# fin div row #}
          {{ author.description | raw }}

          <a href="{{ path("user_show", {'slug' : author.slug}) }}" 
          class="btn btn-primary">Plus d'infos sur {{author.firstName}}</a>
          </div> {# fin div alert-light #}

        <div class="alert alert-light" id="comment">
        {# ici on cible directement l'id="comment" pour nous emméner directement sur l
        page de commentaire sur booking de réservation  #}
           <h2 class="alert-heading">Votre avis compte !</h2>

            {# si la date de ahjour'hui et bine superieur a la date
            de fin de notre réservation donc que on et parti  de l'appartement alors on veut maintnant le note  #}
             {% if date() > date(booking.endDate) %}
               {% set comment = booking.ad.commentFromAuthor(app.user) %}             
                 {% if comment is not null %}
                    <blockquote>
                       {{comment.content}}
                    </blockquote>
                    
                    <strong>Note : </strong> 
                    {% include 'partials/rating.html.twig' with {'rating' : comment.rating} %}
                  
                  {% else %}
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                      <button type="submit" class="btn btn-success">Confirmer !</button> 
                    {{ form_end(form) }}
                  {% endif %}
                {% else %}
               {# si non  #}
              <p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet !</p>
             {% endif %}
        </div> {# fin div alert alert-light #}
       </div> {# fin div col 1 detail de la reservation  #}
      
       <div class="col">
          <div class="alert alert-light">
              <h2 class="alert-heading">Votre hébergement</h2>

              <h4>
                <a href="{{ path('ads_show', {'slug' : ad.slug}) }}">
                {{ad.title}}
                </a>
              </h4>

               <img src="{{ad.coverImage}}" alt="Image de {{ad.title}}"
               class="img-fluid">

               {{ad.content | raw }}

               <a href="{{ path('ads_show', {'slug' : ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>

          </div> {# fin div alert-light #}
       </div> {# fin div col 2  detail de l'appartement #}
   </div> {# fin div row #}
 </div> {# fin div container #}

{% endblock %}