src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Comment;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"title"},
 * message="Une autre annoce possède déjà ce titre, merci de le modifier"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères !",
     * maxMessage="Le titre ne peut pas faire plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\length(min=100, minMessage="Votre description ne peut pas faire moins de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="Ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initializer le Slug
     * 
     *@ORM\PrePersist
     *@ORM\PreUpdate
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un author par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        // esque par mis tout ces commentaire qui sont lies à l'annnce la quelle je suis entrain de mis placer 
        // esque l'author est le meme l'author de qui mais parle ici en parametre de injection
        foreach($this->comments as $comment) {
            // pour chaque commentaire que j'ai dans cette annonce 
            if($comment->getAuthor() === $author) return $comment;
            // je veut verifie si l'author de commentaire se le meme que l'author ici alors je veut returne ce commentaire 
        }
        // si non je veut returne nulle si j'ai pas de commentaire 
        return null;
    }
    
    /**
     * Permet d'obtenir la moyenne globale des notes obtenu pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings(){
        // Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0); // par defaut le total serra a zero 

        // Faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);
        
        return 0;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jour d'occupation
     */
    public function getNotAvailableDays() {
        // ici tabeau vide pour le moment qui contiendra par la suite le journées ou l'appart ne serra pas disponible 
        $notAvailableDays = []; 

        // on vas boucle sur nous réservation pour chaque une de réservation je connais pour chque une la date de arrive et de départ
        foreach($this->bookings as $booking) {
            // Calculer les jours qui se trouvent entres la date d'arrivée et de départ
            // ici on calcule 24h * 60 minute * 60 seconde minute 
            // on compare la date de arrive et la date de depart au forma timestamp
            // la function range()de PHP Créé un tableau qui contient chaques étape existant entre deux nombres
            // resultar = [10, 12, 14, 16, 18, 20] donc range compte et sotant de deux a chaque fois ça depand de sthep que on lui donne en dernier parametre ça peux etre 2 ou 4 ou 5 ou plus etc...
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60 
            );

            // Tableau des chaînes des caractères de mes journées
            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            // ici haut on transforma le resultat obtenu en une DateTime que on a obtenu avec range() on le transforme avec array_map
            // pour pouvoir le lire et le utiliser
       
            // je vais fussioner les deux tableau 
            $notAvailableDays = array_merge($notAvailableDays, $days);

        }
        return $notAvailableDays;
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?user
    {
        return $this->author;
    }

    public function setAuthor(?user $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use App\Repository\AdRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class AdController extends AbstractController
{
    /**
     * Permet de afficer la liste des annonces
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo){  
        // function findAll() du repository 
        // Elle perment de récupérer tous les enregistrements de la table visée
        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }

     /**
     * Permet de créer une annonce
     * 
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     * 
     * isgranted permet de s'assurer que l'utilisateur possède un certain rôle
     * Rappel: le ROLE_USER C'est le rôle que l'on donne par défaut à tous les utilisateurs connectés
     * 
     * @return Response
     */
    // ici on injecte la Request $request pour recupere les 
    // donne de formuaire apre sa soumition en POST de la page new.html.twig 
    public function create(Request $request, ObjectManager $manager){
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);
         
        $form->handleRequest($request);
    
        if($form->isSubmitted() && $form->isValid()){
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            // ici on fait le lien entre l'author et les annonce pour afficher les author des chaque annonce 
            // Rappel : on oblient le utilisateur connecté avec la function getUser()
            // Disont que l'AUTHOR de cette annonce ce l'utilisateur que c'est connnecté 
            $ad->setAuthor($this->getUser());
            
            $manager->persist($ad); // on demande de se prepare pour recevoir les information en bdd
              $manager->flush(); // on les enregistre en bdd  definitevement 

              $this->addFlash(
                // Flash pour prevenire le visiteur de enregistement 
                    'success',
                    "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !" 
                 );  

              return $this->redirectToRoute('ads_show', ['slug' => $ad->getSlug()
              ]);     
            }

              return $this->render('ad/new.html.twig', ['form' => $form->createView()]
            );
    }

    /**
     * Perment de afficher le formulaire de edition avec de expression de securite
     * 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * 
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", 
     * message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier") 
     * @return Response
     */

    // ici je veut enpeche l'utilisateur de edite un annonce si ne pas lui même l'Author
    // non seulement que la personne soit garanti utilisateur connecté avec 
    // isgranted role_user et que soit le même utilisateur que l'author de annonce 
    // Annotation security Permet plus de flexibilité que isgranted grâce aux "Expression"
    // Les expressions de sécurité Sorte de syntaxe logique exprimant des conditions d'accés
    public function edit(Ad $ad, Request $request, ObjectManager $manager){
        $form = $this->createForm(AdType::class, $ad);
         
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }
            
                $manager->persist($ad); // on demande de se prepare pour recevoir les information en bdd
                $manager->flush(); // on les enregistre en bdd  definitevement 

                $this->addFlash(
                    // Flash pour prevenire le visiteur de enregistement 
                        'success',
                        "Les modification de l'annonce <strong>{$ad->getTitle()}</strong> ont bien été enregistrées !" 
                    );  

              return $this->redirectToRoute('ads_show',
               ['slug' => $ad->getSlug()
              ]);     
            }


        return $this->render('ad/edit.html.twig', [
            'form' =>  $form->createView(),
            'ad' => $ad

        ]);
    }
     
    /**
     * 
     * Permet d'afficher une seule annonce
     * 
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad) {
        // je recupere l'annonce qui corespond au slug ! 
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
            ]);
    } 


    
     /**
      * Permet de supprimer une annonce 
      *
      * @Route("/ads/{slug}/delete", name="ads_delete")
      *
      * @Security("is_granted('ROLE_USER') and user == ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressource")
      * rappele:secutity permet d'analyser plus finement la situation que isgranted
      *
      * @param Ad $ad
      * @param ObjectManager $manager
      * @return Response
      */
    public function delete(Ad $ad, ObjectManager $manager) {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien éte supprimée !"
        );
        
        return $this->redirectToRoute("ads_index");
    }


}

templates/ad/_ad.html.twig
         {# set url c'est une variable de factorisation pour les Url de
           nous lien si un jour on veut changer
           on change ici et ce tout pour nous trois
           lien qui il y'a ici pour l'url image, 
           le url de title et l'introduction #}
{% set url = path('ads_show', {'slug' : ad.slug}) %}
          <div class="col-md-4">
             <div class="card bg-light mb-3">
                 <div class="card-header text-center">
                    {{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ')}} &euro; / nuit</strong> <br>
                    
                    {% if ad.comments|length > 0 %}
                       {% include 'partials/rating.html.twig' with {'rating' : ad.avgRatings} %}
                    {% else %}
                    <small>Pas encore noté</small> 
                    {% endif %}
                    
                 </div> {# fin div header text-center se pour centre le text au centre #}
                 
                  <a href="{{ url }}">
                     <img src="{{ ad.coverImage }}" alt="Imade de annonce"
                     style="height:200px; width:100%; display: block">
                  </a>

                 <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ url }}">
                          {{ ad.title }}
                        </a>
                     </h4>
                       <p class="card-text">
                           {{ad.introduction}}
                       </p>
                      <a href="{{ url }}" class="btn btn-primary float-right">En savoir plus !</a>
                       {# Si il y a quel'qu'en qui et connecté et en plus de ça l'utilisateur connecte se le meme
                        qui a créer cette l'annonce  alors on afficera le lien #}
                        {# Attention en twig on utilise le == mais pas le === #}
                     {% if app.user and app.user == ad.author  %}
                        <a href="{{ path('ads_edit', {'slug' : ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>  
                     {% endif %}
                 </div> {# fin card-body #}
             </div> {# fin card  bg-light mb-3 se pour la culeur light de fond et mb-3 se le marge bottom #}
         </div>  {# fin col-md-4  ça veut dire que je vais avoir 3 colone avec le col-md-4 #}

templates/ad/_collection.html.twig
{# TAMPLETE corps et basse de deux formulaire que se soit de EDITION ou de CREATION  #}


{# ici on appele le fichier edit dans la tamplete de formulaire a la place de theme _self on appele 'ad/_collection.html.twig' #}
{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres image !</p>
   
   {{ form_widget(form) }}

   {# Rappel: les inputs non nommés 
   Un champs qui n'a pas d'attribute "name" n'eest pas envoyé au serveur #}
    <input type="hidden" id="widgets-counter" value="0">

   <div class="form-group">
       <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
       </button> {#  fin de button attention il doit etre un button si non vas se summetre quand on apuis deçu #}
   </div> {# fin div form-group #}
{% endblock %}

{% block _ad_images_entry_row %}
  {{ form_widget(form) }} {# ici on enleve le label de notre champ des 2 image 0 et 1 #}
{% endblock %}

{# ici se le sous formulaire  d'ajout de image et legende (function Entry) #}
{% block _ad_images_entry_widget %} 
   <div class="form-group" id="block_{{id}}">
   {{ form_errors(form) }}
      <div class="row">
          <div class="col-10">
            <div class="row">
               <div class="col">
                     {{ form_widget(form.url) }} {# je ce que ma variable ImageType a un Url #}
                     {{ form_errors(form.url) }} {# donne moi les erroe de champs Url de l'image  #}
                  </div> {# fin div col premier conlone #}

                  <div class="col">
                     {{ form_widget(form.caption) }} {# je ce que ma variable ImageType a un Caption se une legende #}
                     {{ form_errors(form.caption) }} {# donne moi les erroe de champs Caption legende  #}
                  </div> {# fin div col second colone #}
               </div> {# fin div row premier #}
           </div> {# fin div col-10 #}
         <div class="col-2">
             {# on ajoute la data-action="delete" sur le button pour pouvoir le appeler en jquery pour le supprime si on le shuaite #}
             {# on ajoute le data-target="#block_{{id}}" quel est l'image que je veut supprime et on le cherche par l'id et que se trouve dans la div form-group  #}
            <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">x</button>
         </div> {# fin div col-2 #}
      </div> {# fin div row premie #}
   </div> {# fin div form-group #}
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{# Ici on montre l'affichage d'un formulaire d'eddition #}

{% block title %}Edition d'une annonce{% endblock %}

 {% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
     <div class="container">
        <h1>Modifier l'annonce : {{ ad.title }}</h1>

       {# il fu pas oublier de configure dans config/packages:twig.yaml
        la ligne suivante pour les formulaire bootstrap 4 
           form_themes: ['bootstrap_4_layout.html.twig'] #}
        {{ form_start(form) }}

        {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
 
        {{ form_end(form) }}
     </div> {# fin div container #}
{% endblock %}


    
   {# ici on appele les function neccesaire au 
   functionement de formulaire d'creation ou de edition
   que on a declare dans le dossier plublic JS/ad.js #}
    {% block javascripts %}
       <script src="{{ asset('build/js/ad.js') }}"></script>
    
    {{ encore_entry_script_tags('js/ad') }}
   {% endblock %}  

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces{% endblock %}

{% block body %}

<div class="container">
   {# my-3 ça veut dire marge haut et bas #}
   <h1 class="my-5">Voici les annonces de nos hôtes !</h1>

   <div class="row">
       {% for ad in ads %}

          {% include 'ad/_ad.html.twig' %}
          
       {% endfor %}
   </div> {# fin row #}
</div> {# fin div container#}

{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   {{ad.title}}
{% endblock %}

{% block body %}

   <div class="ad-title" style="background-image: url({{ ad.coverImage }})">
     <div class="container">
        <h1>{{ad.title}}</h1>
          <p>{{ad.introduction}}</p>
             <p class="h2">
             <strong>{{ad.rooms}} chambres</strong> pour <strong>{{ad.price | number_format(2, ',', ' ')}} &euro;</strong> par nuit
             {# filtre number-format se  2 = deux cifre  qui sont separe par la virgule = ,  et qui a l'espace de millier = ' ' que on met entre les grand nombre #}
             </p>  
              <a href="{{ path('booking_create', {'slug' : ad.slug}) }}" class="btn btn-primary">Réserver !</a>
              {# Si il y a quel'qu'en qui et connecté et en plus de ça l'utilisateur connecte se le meme
               qui a créer cette l'annonce  alors on afficera le lien #}
               {# Attention en twig on utilise le == mais pas le === #}
              {% if app.user and app.user == ad.author  %}
              <a href="{{ path('ads_edit', {'slug' : ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>  
              
              <a href="{{ path('ads_delete', {'slug' : ad.slug}) }}" class="btn btn-danger onclik="return confirm(`Êtes vous sur de vouloir supprimer l'annonce : {{ad.title}} ?`)">Supprimer l'annonce</a>
              {% endif %}
     </div> {# fin du div container #}
   </div> {# fin div class="ad-title" #}

   <div class="container">
       <div class="row">
           <div class="col-md-8 mb-3">
                {{ ad.content | raw }} {# filtre RAW se pour pas afficher les balise enleve
                 la securite de twig si il y a une comment ici le balise <p>Paragraph</p>#}
      
                <div class="bd-example">
                    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                      <ol class="carousel-indicators">
                        {% for image in ad.images %}
                        <li data-target="#carouselExampleCaptions" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                      </ol>
                <div class="carousel-inner">
                        {% for image in ad.images %}
                          <div class="carousel-item {% if loop.first %}active{% endif %}">
                              <img src="{{ image.url }}" class="d-block w-100" alt="First slide">
                              <div class="carousel-caption d-none d-md-block">
                                  <h5>{{ ad.title }}</h5>
                                  <p>{{ image.caption }}</p>
                              </div> {# fin div carousel-caption #}
                          </div>  {# fin div carousel-item active #}
                        {% endfor %}
                </div> {# fin div carousel-inner #}
                              <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                              </a>
                              <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                              </a>
                  </div> {# fin div id="carouselExampleCaptions #}
              </div> {#  fin div bg-exemple carrouselle #}
              
              
              <hr>

            {% if ad.comments|length > 0 %}
               <h2 class="mb-3">Commentaires de nos voyageurs :</h2>
                
                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                       <div class="row align-items-center">
                          <div class="col">
                             Note globale donnée par nos voyageurs
                          </div> {# fin div col #}

                          <div class="col">
                            {% include 'partials/rating.html.twig' with {'rating' : ad.avgRatings} %}
                             <br>
                             <small>(Calculée sur {{ ad.comments|length }} avis)</small>
                          </div> {# fin div col #}
                       </div> {# fin div row #}
                    </h4>
                </div> {# fin div alert-info #}
               
               {# pour chaque commentaire dans annonce de commentaire  #}
               {% for comment in ad.comments %}
                  <div class="bg-light rounded mb-3 py-3 px-3">
                     <strong>{{ comment.author.firstName }}</strong> a dit :
                     <blockquote>
                        {{comment.content}}
                     </blockquote>
                     <strong>Note donnée : </strong>

                  {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}

                  </div> {# fin div bg-light rounded #}
               {% endfor %}
            {% else %}
               <h2>Cette annonce n'a pas encore reçu de commentaires .</h2>
            {% endif %}
            

            </div> {# din div col-md-8 mb-3 se pour que ils
               passent en deçu une de l'autre sur le mobile et mb-3 se pour margin en bas = margin bottom #}


           <div class="col">
           {# ad.author se une instance de la class User donc est lier au Entite User #}
               {% set a = ad.author %} {# declaration de variable author 
               pour l'appel veut que on appele plusieur fois on declare le 
               set a = ad.author et on fait ici apele a la variable (a) ici parti author #}
                <div class="row mb-3 align-items-center">
                    <div class="col-3">
                    <a href="{{ path('user_show', {'slug' : a.slug}) }}">
                        <img src="{{a.picture}}" class="avatar avatar-medium" alt="Avatar de {{a.fullName}}">
                    </a>
                    </div> {#  fin div col-4 #}
                    <div class="col">
                        <a href="{{ path('user_show', {'slug' : a.slug}) }}">
                            <h3>{{a.fullName}}</h3> {# cette function fullName on la declare dans la Entity User #}
                            {# ici a.ads | length : ça me donne le tableau et le nombre des element que il contien 
                            je le fait passer par le filtre length pour avoir la longeur de cette tableau #}
                        </a>        
                            <span class="badge badge-primary">{{a.ads | length}} annonces</span>
                    </div> {# fin div col #}
                </div> {# fin div row  se pour avoir plusieur collone #}
              <div>
                {{a.description | raw }} 
                {# RAPPEL: le filtre TWIG "RAW" Permet de ne pas échaper les caractères spéciaux HTML #}
              </div> {# fin div qui contient le paragraph #}
           </div> {# fin div col #}
       </div> {# fin div row #}
   </div> {# fin div container #}


{% endblock %}